### ISSUE TITLE
Use cursor: pointer on clickable chips / tag

### ISSUE THREAD

**Issue by blazeu** [coala/projects#417]
It is clickable so the cursor should be `pointer` when hovering over those.
![image](https://user-images.githubusercontent.com/1438859/32725239-e3f39b16-c8a6-11e7-9fa2-04e51e6fd8ff.png)

difficulty/newcomer

**Comment by tkhurana96** [comment]
Hi @blazeu, I would like to take this issue, if you don't mind

**Comment by blazeu** [comment]
Sure, anyone is free to take it.
See coala.io/newcomer first.

**Comment by tkhurana96** [comment]
@blazeu if you don't mind me asking, where in the code does the changes for this needs to be made, that is, in which files to add my code for making these chips clickable ?

**Comment by blazeu** [comment]
It's "hoverable", the chips is already "clickable".

Use inspect element on your browsers to see which css to modify.

If you can't do that, then you're not fitted for solving this issue.

**Comment by tkhurana96** [comment]
@blazeu, I found where to add what code, when I asked you for help, I was confused as to where were these chips being displayed because I hadn't seen them on coala site, but then I found out that it was the `projects` repo under `coala`, so then I figured it out, that I need to update this: 
`.chip {
  display: inline-block;
  height: 32px;
  font-size: 13px;
  font-weight: 500;
  color: rgba(0, 0, 0, 0.6);
  line-height: 32px;
  padding: 0 12px;
  border-radius: 16px;
  background-color: #e4e4e4;
  margin-bottom: 5px;
  margin-right: 5px;
}` to 
`.chip {
  display: inline-block;
  height: 32px;
  font-size: 13px;
  font-weight: 500;
  color: rgba(0, 0, 0, 0.6);
  line-height: 32px;
  padding: 0 12px;
  border-radius: 16px;
  background-color: #e4e4e4;
  margin-bottom: 5px;
  margin-right: 5px;
  cursor: pointer;
}` in file `/resources/vendors/materialize/css/materialize.css`

**Comment by tkhurana96** [comment]
#421 Here is the PR, please have a look :smile:

**Comment by riouwa** [comment]
Can I continue this one?
