### ISSUE TITLE
Create corobo project

### ISSUE THREAD

**Issue by jayvdb** [coala/projects#498]

**Comment by nemaniarjun** [comment]
[Following]

**Comment by jayvdb** [comment]
@nemaniarjun , you have some ideas?

We have a general problem with the bot in that it needs security hardening, esp. ensuring that only people in certain teams can run various commands (and that needs to be tested and verifiable, which is a bit of a problem in @errbot) .  See high priority list of issues in the repo.

Many of these hardening enhancements also require IGitt enhancements, as it doesnt have teams yet, so between corobo and IGitt there is definitely a project.  Someone just needs to write it up.

**Comment by jayvdb** [comment]
IMO any GSoC proposal for corobo needs to include a decent amount of improvements to errbot, especially around security.

**Comment by meetmangukiya** [comment]
More ideas:

1. Better tests and test infrastructure. 
2. Look through the plugin proposals and implement them based on the needs.
3. Improving labhub and security. 
4. Better configurability.

### Better tests and testing infrastructure

Currently we have really hacky tests. We are not using the TestCase provided by the errbot itself in some complex plugins like labhub, and labhub is one really important plugin providing most used functionality of corobo. 
I think one can investigate the current needs of the tests in labhub that are not met by errbots provided TestCase and implement it upstream. IIRC the reason was mocking.

### Implement plugin proposals 

Conduct some community surveys to determine which is the most demanded one?

### Improving labhub and security

There are some security fixes that needs to be made in labhub. We want access controls in coala based on GitHub teams. This is actually very coala specific. 

I'd propose we try to make the ACL plugin provided by errbot extensible, and then extend it to make it coala specific.

### Better configurability

We want corobo to be easily usable by other orgs, i.e. allow granular configurability for all org specific details.. and make it more and easily adaptable in general.
