### ISSUE TITLE
Update the mentors page with 2019 people

### ISSUE THREAD

**Issue by abhishalya** [coala/projects#777]
We should update the page with 2019 mentors instead of 2018.

**Comment by faraz16iqbal** [comment]
Hi, is it possible for me to work on this update?

**Comment by abhishalya** [comment]
Yes! Why not. Assigned

**Comment by faraz16iqbal** [comment]
Can you please guide me as to how to access the information?

**Comment by abhishalya** [comment]
Wouldn't it be nice if you could figure it out ;)

**Comment by chttrjeankr** [comment]
@faraz16iqbal, are you still working on this?

**Comment by abhishalya** [comment]
@chttrjeankr Do you want to take up this issue?

**Comment by chttrjeankr** [comment]
> @chttrjeankr Do you want to take up this issue?

Sure! I'd have to go through the newcomers' procedure first. I can then start working on it.

**Comment by abhishalya** [comment]
Assigned to @chttrjeankr due to inactivity of previous assignee.

**Comment by chttrjeankr** [comment]
Thanks for assigning. :rocket: 

I think you mean this [Mentors Page](https://projects.coala.io/#/mentors). 

The trace led me to realize the [`resources/js/directives/mentors.js`](https://github.com/coala/projects/blob/3857d95e0e2d1697fdc8cc67ab8a117e4db0c749/resources/js/directives/mentors.js) file [fetches](https://github.com/coala/projects/blob/3857d95e0e2d1697fdc8cc67ab8a117e4db0c749/resources/js/directives/mentors.js#L11) data from [`data/projects.liquid`](https://github.com/coala/projects/blob/master/data/projects.liquid) which in turn fetches data from [`site.projects`](https://github.com/coala/projects/blob/master/data/projects.liquid#L4).

And since the site already has projects [listed](https://projects.coala.io/#/projects), I don't understand why it isn't automatically updating. I'm a bit new to JS so maybe I'm missing something? Could you help @abhishalya?

**Comment by chttrjeankr** [comment]
Figured out [what to change](https://github.com/coala/projects/blob/3857d95e0e2d1697fdc8cc67ab8a117e4db0c749/resources/js/directives/mentors.js#L13). Discussing an appropriate solution would be needed.

The current code makes a list of all mentors who are in a project that has a status of NOT `completed`.
I don't think we want that to happen.

So we have multiple options for the mentors page:
1.  To list all mentors from all projects that are complete.
2.  To list ALL mentors disregarding the project's status.
3.  To list only mentors from `GSoC19` of projects that are complete.
4.  To list mentors from all `GSoC19` projects.
5.  To make a dynamic mentors page to have mentors of GSoC for the present year. (not very suitable as coala [is not in GSoC every year](https://summerofcode.withgoogle.com/organizations/?sp-search=coala)) (this has been tried earlier #709)

The choice would depend on what exactly do we want the `Mentors` page to portray. Waiting for your views on the above. @abhishalya

**Comment by abhishalya** [comment]
@chttrjeankr  Right, good research around this. So we want to change the existing implementation a bit, what we need is to get all mentors for the completed projects in latest program year (right now its 2019). In other words we need to list all mentors for all official (completed) projects for the latest GSoC coala participated in.

Now this might be a bit tricky with the existing data, you can have a look at https://github.com/coala/projects/pull/729 for reference. You can checkout webservices https://gitlab.com/coala/landing and see doing this is better with or without webservices involved.

**Comment by chttrjeankr** [comment]
> So we want to change the existing implementation a bit, what we need is to get all mentors for the completed projects in latest program year (right now its 2019). In other words we need to list all mentors for all official (completed) projects for the latest GSoC coala participated in.

@abhishalya The best solution to this would be if each project has a date/year attached to it. We can then filter by `year`(latest program year), `tag`(GSoC) and `status`(completeness) and get the required projects and their mentors.

Or, having the tags be different. Rather than using `GSoC`, we may introduce `GSoC19` tags, and similarly for `RGSoC` and other annual programs too, to maintain uniformity. This would need some manual updating to the project structures (I'm not sure where [`site.projects`](https://github.com/coala/projects/blob/master/data/projects.liquid#L4) is fetching data from)

> Now this might be a bit tricky with the existing data, you can have a look at #729 for reference. You can checkout webservices https://gitlab.com/coala/landing and see doing this is better with or without webservices involved. (webserivices might not be in good shape right now)

As far as this is concerned, the way to [fetch results](https://github.com/coala/projects/pull/729/files#diff-b7c96b83e41797041ea5067055f8b2afR389-R391) in #729 doesn't seem to work anymore. And yeah, webservices are in a pretty bad shape right now, with the last commit over a year ago. So, maybe involving that wouldn't be the best idea.
